tylp/memo-draw

README.md

Testing Github branch workflow.

Add rules in memodraw ReadMe

---

.github/workflows/node.js.yml
package-lock.json
package.json
postcss.config.js
src/pages/_app.tsx
src/pages/index.tsx
tailwind.config.js

install tailwind and set examples

---

README.md
package.json

This adds a eslint check script in package.json

Add eslint script

---

next-env.d.ts
package-lock.json
package.json

Retreive updated readme and npm script

Merge main into user-interface

---

CONTRIBUTING.md

Update component naming convention #28

---

src/components/Common/Layout/Layout.tsx
src/components/Common/SectionTitle/SectionTitle.spec.ts
src/components/Common/SectionTitle/SectionTitle.tsx
src/components/Common/index.ts
src/components/Home/ProfileSelector/ProfileSelector.tsx
src/pages/index.tsx

Yo @adrien-nf  tu peux tester de merger ça ? ça ne va rien casser tkt fréro

brand new SectionTitle !

---

src/pages/room/[id].tsx

add copy button in room

---

server/classes/Storage/SessionStorage.ts
server/factories/ProfileFactory.ts
server/services/FakeNameGeneratorService.ts
server/services/RandomEnumPickerService.ts
src/hooks/useSocket.ts

generate profile through a factory

---

server/classes/Room.ts
server/classes/sockets/IndexSocketBinder.ts
server/factories/RoomFactory.ts
src/components/Room/Id/UserProfile.spec.ts
src/pages/room/[id].tsx

add creator player id to room

---

server/services/FakeNameGeneratorService.test.ts
server/services/FakeNameGeneratorService.ts
server/services/IdGeneratorService.test.ts
server/services/IdGeneratorService.ts
server/services/SocketIdentifierService.test.ts
server/services/SocketIdentifierService.ts

update tests for services

---

next-env.d.ts
package-lock.json
package.json

Dependabot detected vulnerabilities in next <11.1.0. This PR upgrade its version to take care of these issues.

Fix next security issue

---

server/classes/Application.ts
server/classes/Storage/SessionStorage.ts
server/classes/sockets/CommonSocketBinder.ts
server/factories/AvatarFactory.test.ts
server/services/RandomEnumPickerService.ts
src/hooks/useSocket.ts

load profile from user's local storage

---

server/classes/Player.ts
server/services/SocketIdentifierService.ts
src/components/Common/Button/Button.spec.ts
src/components/Common/Button/Button.tsx
src/components/Home/ProfileSelector/ProfileSelector.spec.ts
src/components/Home/ProfileSelector/ProfileSelector.tsx

renamed interfaces

---

server/classes/Application.ts
server/classes/Game.ts
server/classes/Room.ts
server/classes/Storage/SessionStorage.ts
server/classes/sockets/CommonSocketBinder.ts
server/classes/sockets/GameSocketBinder.ts
server/classes/sockets/RoomSocketBinder.ts
server/classes/sockets/namespaces/RoomNamespaceBinder.ts
server/factories/AvatarFactory.test.ts
server/services/RandomEnumPickerService.ts
src/components/Room/GameView/GameView.tsx
src/components/Room/LobbyView/LobbyView.tsx
src/hooks/useLocalStorage.ts
src/hooks/useSocket.ts
src/pages/room/[id].tsx
src/services/EnvironmentChecker.ts

Separate concerns of lobby

---

server/classes/Game.ts
server/classes/Room.ts
server/classes/Storage/PlayerRoomStorage.ts
server/classes/sockets/GameSocketBinder.ts
src/components/Room/GameView/GameView.tsx
src/components/Room/GameView/UserProfile.spec.ts
src/components/Room/GameView/UserProfile.tsx
src/pages/room/[id].tsx

setup player turns system

---

server/classes/sockets/RoomSocketBinder.ts
src/components/Room/LobbyView/LobbyView.tsx

Messages sent by a player should be trimmed

---

src/components/Room/GameView/GameView.tsx
src/components/Room/LobbyView/LobbyView.tsx
src/hooks/useLocalStorage/useLocalStorage.ts
src/hooks/useLocalStorage/useLocalStorage.types.ts
src/hooks/useSocket.ts
src/pages/index.tsx
src/pages/room/[id].tsx

add enum for local storage keys

---

server/services/FakeNameGeneratorService.ts

Change generated names

---

server/classes/sockets/CommonSocketBinder.ts
src/components/Home/ProfileSelector/ProfileSelector.tsx
src/pages/index.tsx

Add a randomize avatar button

---

src/components/Common/Layout/Layout.tsx

reduced padding in layout

---

src/components/Lobby/GameView/GameView.tsx
src/components/Lobby/LobbyView/LobbyView.tsx
src/components/Lobby/LobbyView/UserCard.tsx
src/hooks/useSocket.ts
src/pages/Homepage/Homepage.tsx
src/pages/JoinLobby/JoinLobby.tsx
src/pages/Lobby/Lobby.tsx
src/services/SocketEventEmitter.ts

SEM is now a static class

---

server/classes/Lobby/Game.ts
server/classes/Lobby/GameMode/AnarchyGameMode.ts
server/classes/Lobby/GameMode/ClassicGameMode.ts
server/classes/Lobby/GameMode/GameMode.ts
server/classes/Lobby/GameMode/GameModeFactory.ts
server/classes/Lobby/GameMode/NormalGameMode.ts
server/classes/Lobby/Lobby.ts
server/classes/StylingBuilder.ts
server/classes/sockets/LobbySocketBinder.ts
server/enums/GameProperties.ts
server/facades/LobbyFacade.ts
server/services/LobbyService.ts
src/components/Common/Button/Button.tsx
src/components/Lobby/LobbyView/GameSetting/GameSetting.tsx
src/components/Lobby/LobbyView/LobbyView.tsx
src/i18n.ts
src/services/SocketEventEmitter.ts

added game mode

---

package-lock.json
package.json
server/classes/sockets/GameSocketBinder.ts
src/components/Lobby/GameView/Canvas/Canvas.tsx
src/components/Lobby/GameView/GameView.tsx
src/hooks/useSocket.ts
src/hooks/useSocketLobby.ts
src/pages/Lobby/Lobby.tsx
src/services/NetworkManager/NetworkManager.ts
src/services/SocketEventEmitter.ts

Share drawing between players

---

server/facades/LobbyFacade.test.ts
server/services/FakeNameGeneratorService.test.ts
server/services/FakeNameGeneratorService.ts
server/services/ProfileValidatorService.ts

add tests and set max username length

---

src/components/Lobby/GameView/GameView.tsx
src/components/Lobby/LobbyView/LobbyView.tsx
src/pages/Lobby/Lobby.tsx

added button to leave lobby during game

---

src/components/Lobby/GameView/GameView.tsx

can't vote against yourself

---

src/components/Common/Box/Box.tsx
src/components/Lobby/GameView/GameView.tsx
src/i18n.ts
src/pages/Lobby/Lobby.tsx

add spectators

---

src/components/Lobby/GameView/GameView.tsx

updated call of on instead of notify

---

server/classes/Lobby/PlayerErrorVoteManager/PlayerErrorVoteManager.ts
server/facades/LobbyFacade.ts
src/components/Lobby/GameView/PlayerView/Countdown/Countdown.tsx
src/components/Lobby/GameView/PlayerView/PlayerView.tsx

timer displayed during vote

---

src/components/Lobby/GameView/GameView.tsx
src/components/Lobby/GameView/PlayerView/PlayerView.tsx
src/services/VoteTargets/VoteTargets.ts

can't vote against losers anymore

---

src/components/Lobby/GameView/Canvas/Toolbox/BottomToolBox.tsx
src/components/Lobby/GameView/GameView.tsx
src/components/Lobby/GameView/PlayerView/PlayerView.tsx
src/components/Lobby/GameView/PlayersAndSpectators/PlayersAndSpectators.tsx

removed useless prop

---

src/components/Lobby/GameView/PlayerView/PlayerView.tsx

Can t vote against current player because he is excluded instead of player

---

src/components/Lobby/GameView/PlayerView/PlayerView.tsx

vote not sent again

---

server/services/LobbyService.ts

now defaults vote to yes

---

server/classes/Lobby/Game.ts
server/classes/Lobby/GameMode/AnarchyGameMode.ts
server/classes/Lobby/GameMode/ClassicGameMode.ts
server/classes/Lobby/GameMode/GameMode.ts
server/classes/sockets/GameSocketBinder.ts
src/components/Lobby/GameView/GameView.tsx
src/components/Lobby/GameView/PlayerView/PlayerView.tsx

Finish anarchy mode

---

server/services/EnumToArray/EnumToArray.ts
server/services/ProfileValidatorService.ts
src/components/Lobby/LobbyView/LobbyView.tsx
src/pages/Homepage/Homepage.tsx

Catch modified sessions

---

src/components/Common/ProfileSelector/ProfileSelector.tsx

add styles for button

---

src/components/Common/Modal/Modal.tsx
src/components/Lobby/GameView/PlayerView/PlayerView.tsx

positron's position updated to be on the right

---

src/i18n.ts
src/pages/Error/Error.tsx
src/pages/Error/NotFound.tsx
src/pages/index.tsx

error page done

---

server/classes/Lobby/GameMode/ClassicGameMode.ts

Game speeds up according to the number of drawing

---

server/classes/Lobby/Lobby.ts
server/classes/sockets/LobbySocketBinder.ts
server/facades/LobbyFacade.ts
server/services/LobbyService.ts
src/components/Lobby/LobbyView/GameSetting/GameSetting.tsx
src/components/Lobby/LobbyView/LobbyView.tsx
src/pages/Lobby/Lobby.tsx
src/services/SocketEventEmitter.ts

Currently selected game mode should be displayed for all players in lobby view

---

src/components/Lobby/GameView/PlayerView/PlayerView.tsx
src/components/Lobby/GameView/SpectatorView/SpectatorView.tsx

Fix #355 - Set game badge zindex

---

server/classes/StyleBuilder.ts
server/facades/LobbyFacade.ts
src/components/Lobby/GameView/PlayerView/CurrentVote/CurrentVote.tsx
src/components/Lobby/GameView/PlayerView/PlayerView.tsx
src/components/Lobby/GameView/PlayersAndSpectators/PlayersAndSpectators.tsx
src/components/Lobby/UserEtiquette/UserEtiquette.tsx
src/i18n.ts
tailwind.config.js

Closes #345
Closes #346
Closes #347
Closes #349

Should be able to start vote by clicking on user etiquette s icon

---

src/components/Lobby/GameView/Canvas/Canvas.tsx
src/components/Lobby/GameView/PlayerView/PlayerTurnCue/PlayerTurnCue.tsx
src/components/Lobby/GameView/PlayerView/PlayerView.tsx
src/i18n.ts
tailwind.config.js

Add visual cue on player turn starting

---

server/classes/Application.ts
server/classes/Lobby/Game.ts
server/classes/Lobby/Lobby.ts
server/classes/sockets/CommonSocketBinder.ts
server/classes/sockets/GameSocketBinder.ts
server/classes/sockets/LobbySocketBinder.ts
server/facades/LobbyFacade.ts
server/interfaces/IHasSocketRoom.ts
server/interfaces/ISocketJsonable.ts
server/services/LobbyService.ts
src/components/Lobby/GameView/PlayerView/PlayerView.tsx

Next drawing timeout should be handled server side
